version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"  # Expose MongoDB port to the host
    volumes:
      - shop-db:/data/db  # Correct path for MongoDB data storage

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  shop:
    build:
      context: .
    environment:
      ADMIN_FIRSTNAME: admin
      ADMIN_LASTNAME: admin
      ADMIN_USERNAME: admin
      ADMIN_PHONE_NUMBER: 09122211111
      ADMIN_ADDRESS: Tehran-tehran
      PORT: 8000
      HOST: 0.0.0.0  # Bind to all interfaces to allow external access
      DATABASE_URL: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
    ports:
      - "27017:27017"  # Expose app on port 8000
        
volumes:
  shop-db: